### PR TITLE
Fix for issue 50, manifests only when Cabin is set for IO

### LINKED ISSUE #50: Bad geoip lookup returns invalid hash
Please see https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/298#issuecomment-156066999

### PR DESCRIPTION
**Pull request by guyboertje**
fixes #50

### CODE REVIEW

**Comment by guyboertje** [comment]
@andrewvc - Please review (and enjoy)

**Comment by jsvd** [comment]
wow so
1. `get_geo_data` calls `get_geo_data_for_ip` which can raise 2 exceptions.
2. if `get_geo_data_for_ip` works then it returns an object with hierarchy `[GeoIP::City, #<Class:0x782e409f>, Struct, Enumerable, Object, Kernel, BasicObject]`
3. if not, it caches the exceptions and calls `@logger.error` which returns and object with hierarchy `[Hash, JRuby::Generator::Iterators, Enumerable, Object, Kernel, BasicObject]`
4. the filter method then takes the return of `get_geo_data` and does `geo_data.nil? || !geo_data.respond_to?(:to_hash)` which will always return true because both `GeoIP::City` and Hash respond to `to_hash`
5. in the event of @logger.error injecting something weird to its returning hash (like an IO object) we see this problem.

@guyboertje I'm wondering if we should change the check in filter to ensure the return is either a Struct or more precisely a GeoIP::City (though not sure if this is always true)

File: spec/filters/geoip_spec.rb [hunk 1]
```diff
@@ -184,15 +185,46 @@
...
 
       sample("ip" => "~") do
-        expect{
-          subject
-          }.to_not raise_error
+        expect{ subject }.to_not raise_error
+      end
+    end
+
+    context "when IO is used for logging" do
```
Comment (jsvd) [inline spec/filters/geoip_spec.rb]: looking at this test I'm not sure if we should try to work with whatever `@logger.error` gives us and ensure that either we get a proper Struct from `get_geo_data` or consider the call failed.
This way we don't have to go into details like "what if Cabin logger uses a StringIO?"

**Comment by guyboertje** [comment]
wow is correct.  In point 3 did you mean catches and not caches?

**Comment by jsvd** [comment]
yes, edited.

**Comment by guyboertje** [comment]
@jsvd @purbon  - FYI, updated code and test

File: lib/logstash/filters/geoip.rb [hunk 2]
```diff
@@ -124,22 +124,24 @@ def register
...
-    
+
     geo_data = nil
 
     geo_data = get_geo_data(event)
 
-    return if geo_data.nil? || !geo_data.respond_to?(:to_hash)
-
-    apply_geodata(geo_data, event)
+    return unless geo_data.respond_to?(:to_hash)
```
Comment (jsvd) [inline lib/logstash/filters/geoip.rb]: from my understanding this will never be executed since we now control the output of get_geo_data and either pump out an empty hash or a geoip struct?

File: lib/logstash/filters/geoip.rb [hunk 3]
```diff
@@ -124,22 +124,24 @@ def register
...
 
-    filter_matched(event)
+    event[@target] = {} if event[@target].nil?
+    geo_data_hash = geo_data.to_hash
+    # don't do anything more if the lookup result is empty
+    if !geo_data_hash.empty?
```
Comment (jsvd) [inline lib/logstash/filters/geoip.rb]: an alternative to line 135 + checking if it's empty here you can just check if geo_data != {}

**Comment by jsvd** [comment]
not necessary but if you find the time would be nice to add an extra test that checks:

* if plugin is `geoip { source => "message"  add_tag => "done" }`
* with an event `LogStash::Event.new("message" => "potatoes")`
* the filtered event won't have tag "done"

File: lib/logstash/filters/geoip.rb (hunk 2 above)
Comment (guyboertje) [inline lib/logstash/filters/geoip.rb]: Its protection against the third party GeoIP code every returning something not hashable.

Comment (andrewvc) [inline lib/logstash/filters/geoip.rb]: :+1: for defensive programming, but this could really use a comment explaining it.

File: lib/logstash/filters/geoip.rb (hunk 3 above)
Comment (guyboertje) [inline lib/logstash/filters/geoip.rb]: True but as I decided that `apply_geodata` should expect and operate on a hash, I moved the hash generation to the `filter` method.  So I test the hash for empty.

One could easily argue that the `get_geo_data_for_ip` method should return a hash, meaning that we cache the hash.  Indeed the mutation of the hash in lines 144 - 148 should be done once before it is stored in the cache.  No need to do it each time, especially if there are many events referencing the same IP address.

**Comment by guyboertje** [comment]
@jsvd - some replies.  I will add the other test you requested.

File: lib/logstash/filters/geoip.rb (hunk 2 above)
Comment (guyboertje) [inline lib/logstash/filters/geoip.rb]: Sure OK.

Also, @andrewvc please comment on my other comment https://github.com/logstash-plugins/logstash-filter-geoip/pull/52#discussion_r44779884

Comment (jsvd) [inline lib/logstash/filters/geoip.rb]: Ok but then it should have the same effect as a failed lookup: event[@target] becomes {} if nil

File: lib/logstash/filters/geoip.rb (hunk 3 above)
Comment (jsvd) [inline lib/logstash/filters/geoip.rb]: :+1:

Comment (andrewvc) [inline lib/logstash/filters/geoip.rb]: @guyboertje I really like the proposal for `get_geo_data_for_ip` to return a hash, but it's not the most important thing for me, so make that determination for yourself :)

Comment (guyboertje) [inline lib/logstash/filters/geoip.rb]: @andrewvc - Noted.  I have created a new issue for that refactor.

**Comment by jsvd** [comment]
LGTM
